[package]
name = "ckbes"
version = "1.0.2"
edition = "2024"
description = "CKB Easy Script is a framework for developing ckb contracts."
license = "MIT"

[dependencies]
blake2ya = "1.0"

[profile.release]
codegen-units = 1
overflow-checks = true
strip = true
